# <font color='gray'>Problema de Negócio - Tratamento de dados de uma plataforma de Empréstimo</font>

![title](imagens/EstudoCaso1.png)

In [247]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.12


In [248]:
# Import
import numpy as np

In [249]:
import warnings
warnings.filterwarnings('ignore')

https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html

In [250]:
# Configuração de impressão do NumPy
np.set_printoptions(suppress = True, linewidth = 200, precision = 2)

## Carregando o Dataset

https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html

In [251]:
dados = np.genfromtxt("dataset1.csv", 
                      delimiter = ';', 
                      skip_header = 1, 
                      autostrip = True, 
                      encoding = 'cp1252')

In [252]:
type(dados)

numpy.ndarray

In [253]:
dados.shape

(10000, 14)

In [254]:
dados.view()

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

Várias colunas estão com o tipo nan. Isso se deve a caracteres especiais no conjunto de dados e a forma como o NumPy carrega dados numéricos e do tipo string. Vamos resolver isso.

## Verificando Valores Ausentes

In [255]:
np.isnan(dados).sum()

88005

https://numpy.org/doc/stable/reference/generated/numpy.nanmax.html

In [256]:
# Vamos retornar o maior valor + 1 ignorando valores nan
# Usaremos esse valor arbitrário para preencher os valores ausentes no momento da carga de dados de variáveis
# numéricas e depois tratamos esse valor como valor ausente
valor_coringa = np.nanmax(dados) + 1
print(valor_coringa)

68616520.0


https://numpy.org/doc/stable/reference/generated/numpy.nanmean.html

In [257]:
# Calculamos a média (variáveis numéricas) ignorando valores nan por coluna
# Usaremos isso para separar variáveis numéricas de variáveis do tipo string
media_ignorando_nan = np.nanmean(dados, axis = 0)
print(media_ignorando_nan)

[54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92         nan         nan         nan         nan         nan     3143.85]


https://numpy.org/doc/stable/reference/generated/numpy.argwhere.html

https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html

In [258]:
# Colunas do tipo string com valores ausentes
colunas_strings = np.argwhere(np.isnan(media_ignorando_nan)).squeeze()
colunas_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [259]:
# Colunas numéricas 
colunas_numericas = np.argwhere(np.isnan(media_ignorando_nan) == False).squeeze()
colunas_numericas

array([ 0,  2,  4,  6,  7, 13])

> Importamos novamente o dataset, separando colunas do tipo string de colunas numéricas.

In [260]:
# Carrega as colunas do tipo string
arr_strings = np.genfromtxt("dataset1.csv",
                            delimiter = ';',
                            skip_header = 1,
                            autostrip = True, 
                            usecols = colunas_strings,
                            dtype = str, 
                            encoding = 'cp1252')

In [261]:
arr_strings

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [262]:
# Carrega as colunas do tipo numérico preenchendo os valores ausentes
arr_numeric = np.genfromtxt("dataset1.csv",
                            delimiter = ';',
                            autostrip = True,
                            skip_header = 1,
                            usecols = colunas_numericas,
                            filling_values = valor_coringa, 
                            encoding = 'cp1252')

In [263]:
arr_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

> Agora extraímos os nomes das colunas.

In [264]:
# Carrega os nomes das colunas
arr_nomes_colunas = np.genfromtxt("dataset1.csv",
                                  delimiter = ';',
                                  autostrip = True,
                                  skip_footer = dados.shape[0],
                                  dtype = str, 
                                  encoding = 'cp1252')

In [265]:
arr_nomes_colunas

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state', 'total_pymnt'], dtype='<U19')

In [266]:
# Separa cabeçalho de colunas numéricas e string
header_strings, header_numeric = arr_nomes_colunas[colunas_strings], arr_nomes_colunas[colunas_numericas]

In [267]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [268]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Função de Checkpoint

**Checkpoint 1**

Vamos criar uma função de checkpoint para salvar os resultados intermédiários. 

NumPy Zipped Data -> extensão .npz

In [269]:
# Função
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [270]:
checkpoint_inicial = checkpoint("Checkpoint-Inicial", header_strings, arr_strings)

In [271]:
checkpoint_inicial['data']

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [272]:
np.array_equal(checkpoint_inicial['data'], arr_strings)

True

## Manipulando as Colunas do Tipo String

In [273]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [274]:
# Vamos ajustar o nome da coluna issue_d para facilitar a identificação da coluna
header_strings[0] = "issue_date"

In [275]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [276]:
arr_strings

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

### Pré-Processamento da Variável issue_date com Label Encoding

In [277]:
# Extrai os valores únicos da variável
np.unique(arr_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15', 'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [278]:
# Vamos remover o sufixo -15 e converter em um array de strings
arr_strings[:,0] = np.chararray.strip(arr_strings[:,0], "-15"); arr_strings[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [279]:
# Extrai os valores únicos da variável
np.unique(arr_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'], dtype='<U69')

In [280]:
# Criamos um array com os meses (incluindo um elemento como vazio para o que estiver em branco)
meses = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']);len(meses)

13

In [281]:
# Loop para converter os nomes dos meses em valores numéricos
# Label Encoding
for i in range(len(meses)):
        arr_strings[:,0] = np.where(arr_strings[:,0] == meses[i], i, arr_strings[:,0])

In [282]:
np.unique(arr_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Pré-Processamento da Variável loan_status com Binarização

In [283]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [284]:
# Extrai os valores únicos da variável
np.unique(arr_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued', 'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [285]:
# Número de elementos
np.unique(arr_strings[:,1]).size

9

In [286]:
# Criamos um array com apenas 3 status
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [287]:
# Checamos agora os valores da variável e comparamos com o array anterior convertendo a variável para valores binários
# Binarização
arr_strings[:,1] = np.where(np.isin(arr_strings[:,1], status_bad),0,1)

In [288]:
# Extrai os valores únicos da variável
np.unique(arr_strings[:,1])

array(['0', '1'], dtype='<U69')

In [289]:
arr_strings[:,1]

array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U69')

### Pré-Processamento da Variável term com Limpeza de String

In [290]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [291]:
# Extrai os valores únicos da variável
np.unique(arr_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [292]:
# Removemos a palavra months (observe o espaço antes da palavra)
arr_strings[:,2] = np.chararray.strip(arr_strings[:,2], " months")
arr_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [293]:
# Mudamos o título da variável
header_strings[2] = "term_months"

In [294]:
# Substituímos os valores ausentes pelo maior valor, em nosso caso 60
arr_strings[:,2] = np.where(arr_strings[:,2] == '', '60', arr_strings[:,2])

In [295]:
arr_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [296]:
# Extrai os valores únicos da variável
np.unique(arr_strings[:,2])

array(['36', '60'], dtype='<U69')

### Pré-Processamento das  Variáveis grade e sub_grade com Dicionário (Tipo de Label Encoding)

In [297]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [298]:
# Extrai os valores únicos da variável
np.unique(arr_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [299]:
# Extrai os valores únicos da variável
np.unique(arr_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
       'G2', 'G3', 'G4', 'G5'], dtype='<U69')

Vamos ajustar a variável sub_grade.

In [300]:
np.unique(arr_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [301]:
np.unique(arr_strings[:,3])[1:]

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [302]:
# Loop para ajuste da variável sub_grade
for i in np.unique(arr_strings[:,3])[1:]:
    arr_strings[:,4] = np.where((arr_strings[:,4] == '') & (arr_strings[:,3] == i), i + '5', arr_strings[:,4])

In [303]:
# Retorna categorias e suas respectivas contagens
np.unique(arr_strings[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
        'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [304]:
# Substituímos valores ausentes por uma nova categoria
arr_strings[:,4] = np.where(arr_strings[:,4] == '', 'H1', arr_strings[:,4])

In [305]:
# Extrai os valores únicos da variável
np.unique(arr_strings[:,4], return_counts = True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
        'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9]))

Vamos remover a variável grade.

In [306]:
# Não precisamos mais da variável grade. Podemos removê-la.
arr_strings = np.delete(arr_strings, 3, axis = 1)

In [307]:
# Nova variável na coluna de índice 3
arr_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [308]:
# Não podemos esquecer de remover a coluna do array de nomes de colunas
header_strings = np.delete(header_strings, 3)

In [309]:
# Nova variável na coluna de índice 3
header_strings[3]

'sub_grade'

Por fim, convertemos a variável sub_grade para sua representação numérica.

In [310]:
# Extrai os valores únicos da variável
np.unique(arr_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
       'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [311]:
# Cria uma lista de chaves
keys = list(np.unique(arr_strings[:,3]))     
keys[0]

'A1'

In [312]:
# Cria uma lista de valores
values = list(range(1, np.unique(arr_strings[:,3]).shape[0] + 1)) 
values[0]

1

In [313]:
# Criamos então o dicionário
dict_sub_grade = dict(zip(keys, values))

In [314]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [315]:
# Loop para substituir a string com as categorias pela representação numérica (frequência)
for i in np.unique(arr_strings[:,3]):
        arr_strings[:,3] = np.where(arr_strings[:,3] == i, dict_sub_grade[i], arr_strings[:,3])

In [316]:
# Extrai os valores únicos da variável
np.unique(arr_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36', '4', '5', '6',
       '7', '8', '9'], dtype='<U69')

### Pré-Processamento da Variável Verification status com Binarização

In [317]:
# Lista com os nomes das variáveis
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [318]:
# Extrai os valores únicos da variável
np.unique(arr_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [319]:
# Usamos a binarização nesta variável
arr_strings[:,4] = np.where((arr_strings[:,4] == '') | (arr_strings[:,4] == 'Not Verified'), 0, 1)

In [320]:
# Extrai os valores únicos da variável
np.unique(arr_strings[:,4])

array(['0', '1'], dtype='<U69')

### Pré-Processamento da Variável url com Extração de ID

In [321]:
# Visualiza amostra dos dados
arr_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ..., 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [322]:
# Extraímos o id ao final de cada url
np.chararray.strip(arr_strings[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [323]:
# Substituímos a url pelo valor do id na url
arr_strings[:,5] = np.chararray.strip(arr_strings[:,5], 
                                      "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [324]:
# Convertemos o tipo para int32
arr_strings[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [325]:
# Parece que esse id está presente na primeira coluna do conjunto de dados.
# Vamos converter para int 32 e comparar
arr_numeric[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [326]:
np.array_equal(arr_numeric[:,0].astype(dtype = np.int32), arr_strings[:,5].astype(dtype = np.int32))

True

Sim, é a mesma informação. Vamos então remover uma das colunas.

In [327]:
# Remove do array de dados
arr_strings = np.delete(arr_strings, 5, axis = 1)

In [328]:
# Remove do array de nome de coluna
header_strings = np.delete(header_strings, 5)

In [329]:
# Nova coluna no índice 5
arr_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [330]:
# Nova lista de colunas
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

In [331]:
# Coluna id
arr_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [332]:
# Coluna id agora faz parte do array de numéricos
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### Pré-Processamento da Variável address com Categorização

In [333]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

In [334]:
# Vamos ajustar o nome da coluna
header_strings[5] = "state_address"

In [335]:
# Extrai nomes e contagens
states_names, states_count = np.unique(arr_strings[:,5], return_counts = True)

https://numpy.org/doc/stable/reference/generated/numpy.argsort.html

In [336]:
# Ordena em ordem descrescente
states_count_sorted = np.argsort(-states_count)

In [337]:
# Imprime o resultado
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ', 'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY', 'KS', 'OK',
        'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK', 'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,  216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,   84,   83,
          74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,   25,   24,   17,   16,   10]))

In [338]:
# Substituímos valores ausentes por zero
arr_strings[:,5] = np.where(arr_strings[:,5] == '', 0, arr_strings[:,5])

In [339]:
np.unique(arr_strings[:,5], return_counts = True)

(array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
        'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,   84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,  341,   57,
         130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,   17,  216,  148,   49,   27]))

Vamos separar os estados por regiões. Referência:
https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [340]:
# Separamos os estados por regiões
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [341]:
# Agora substituímos cada estado pelo id da sua região
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5], states_west), 1, arr_strings[:,5])
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5], states_south), 2, arr_strings[:,5])
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5], states_midwest), 3, arr_strings[:,5])
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5], states_east), 4, arr_strings[:,5])

In [342]:
# Extrai os valores úinicos
np.unique(arr_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

**Você pode modificar os dados, mas não pode modificar a informação!**

## Convertendo o Array

Nosso array de strings agora é um array numérico. Vamos ajustar o tipo de dado.

In [343]:
arr_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [344]:
arr_strings = arr_strings.astype(int)

In [345]:
arr_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [346]:
arr_strings.dtype

dtype('int64')

## Checkpoint com Variáveis do Tipo String Limpas e Pré-Processadas

**Checkpoint 2**

Concluída a primeira parte, vamos gravar o checkpooint.

In [347]:
checkpoint_strings = checkpoint("Checkpoint-Strings", header_strings, arr_strings)

In [348]:
checkpoint_strings["header"]

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'state_address'], dtype='<U19')

In [349]:
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [350]:
np.array_equal(checkpoint_strings['data'], arr_strings)

True

## Manipulando Colunas Numéricas

In [351]:
# Visualiza os dados
arr_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [352]:
# Nomes das colunas
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [353]:
# Não temos valor ausente, pois ao carregar os dados substituímos por um valor arbitrário
np.isnan(arr_numeric).sum()

0

In [354]:
valor_coringa

68616520.0

In [355]:
# Podemos checar se uma coluna foi preenchida com o valor coringa
np.isin(arr_numeric[:,0], valor_coringa)

array([False, False, False, ..., False, False, False])

In [356]:
# Podemos checar se uma coluna foi preenchida com o valor coringa
np.isin(arr_numeric[:,0], valor_coringa).sum()

0

Vamos criar um array de estatísticas, especificamente valor mínimo, máximo e média de cada variável. Usaremos isso noo tratamento de valores ausentes (preenchidos com o valor coringa).

In [357]:
# Criamos um array com valor mínimo, média e valor máximo ignorando nan
# Usaremos essa abordagem para tratamento de valores ausentes
arr_stats = np.array([np.nanmin(dados, axis = 0), media_ignorando_nan, np.nanmax(dados, axis = 0)])

In [358]:
print(arr_stats)

[[  373332.           nan     1000.           nan     1000.           nan        6.         31.42         nan         nan         nan         nan         nan        0.  ]
 [54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92         nan         nan         nan         nan         nan     3143.85]
 [68616519.           nan    35000.           nan    35000.           nan       28.99     1372.97         nan         nan         nan         nan         nan    41913.62]]


In [359]:
arr_stats[:, colunas_numericas]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [360]:
arr_stats[:, colunas_numericas].shape

(3, 6)

### Pré-Processamento da Variável funded_amnt

In [361]:
# Visualiza os dados
arr_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [362]:
arr_stats[0, colunas_numericas[2]]

1000.0

In [363]:
# Ajustamos o conteúdo da coluna
arr_numeric[:,2] = np.where(arr_numeric[:,2] == valor_coringa, arr_stats[0, colunas_numericas[2]], arr_numeric[:,2])

In [364]:
arr_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

### Pré-Processamento das Variáveis loan_amnt, int_rate, installment e total_pymnt

In [365]:
# Nomes das colunas
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [366]:
# Loop para substituir o valor ausente (valor_coringa) pelos valores max do array de estatísticas
for i in [1,3,4,5]:
    arr_numeric[:,i] = np.where(arr_numeric[:,i] == valor_coringa, 
                                arr_stats[2, colunas_numericas[i]], 
                                arr_numeric[:,i])

In [367]:
arr_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

### Trabalhando com o Segundo Dataset

Vamos carregar os dados de cotação USD - EURO. Cada linha do dataset corresponde à taxa de câmbio para um mês em um ano.

In [368]:
# Carrega o segundo dataset
dados_cot = np.genfromtxt("dataset2.csv", 
                          delimiter = ',', 
                          autostrip = True, 
                          skip_header = 1, 
                          usecols = 3)

In [369]:
# Visualiza
dados_cot

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [370]:
# Nomes de colunas
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'state_address'], dtype='<U19')

In [371]:
# Dados
arr_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [372]:
# A coluna 0 do array de strings é o mês
arr_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [373]:
# Vamos atribuir a coluna de mês à variável chamada exchange_rate
exchange_rate = arr_strings[:,0]

In [374]:
exchange_rate

array([ 5,  0,  9, ...,  6,  4, 12])

In [375]:
# Loop para preencher a variável exchange_rate com a taxa correspondente ao mês
# Usamos dados_cot[i - 1] devido a forma como carregamos os meses para comportar o zero
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i, dados_cot[i - 1], exchange_rate)    

In [376]:
exchange_rate

array([1.1 , 0.  , 1.13, ..., 1.12, 1.11, 1.09])

In [377]:
# Onde a taxa de câmbio estiver com zero substituímos pela média
exchange_rate = np.where(exchange_rate == 0, np.mean(dados_cot), exchange_rate)

In [378]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [379]:
exchange_rate.shape

(10000,)

In [380]:
arr_numeric.shape

(10000, 6)

In [381]:
exchange_rate = np.reshape(exchange_rate, (10000,1));exchange_rate.shape

(10000, 1)

https://numpy.org/doc/stable/reference/generated/numpy.hstack.html

In [382]:
# Concatenação dos arrays
arr_numeric = np.hstack((arr_numeric, exchange_rate))

In [383]:
# Inclui o nome da coluna no array de nomes de colunas
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))

In [384]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'], dtype='<U19')

Vamos criar colunas para as taxas de câmbio em USD e EURO.

In [385]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'], dtype='<U19')

In [386]:
# Colunas em USD
columns_dollar = np.array([1,2,4,5])

In [387]:
# Visualiza
arr_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [388]:
# Shape
arr_numeric.shape

(10000, 7)

In [389]:
# Loop pelas colunas USD para aplicar a taxa de conversão para EURO
for i in columns_dollar:
    arr_numeric = np.hstack((arr_numeric, np.reshape(arr_numeric[:,i] / arr_numeric[:,6], (10000,1))))

In [390]:
# Shape
arr_numeric.shape

(10000, 11)

In [391]:
# Visualiza
arr_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

Vamos expandir o cabeçalho com as novas colunas.

In [392]:
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[columns_dollar]])

In [393]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [394]:
header_numeric = np.concatenate((header_numeric, header_additional))

In [395]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [396]:
header_numeric[columns_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[columns_dollar]])

In [397]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD', 'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [398]:
columns_index_orderx_order = [0,1,7,2,8,3,4,9,5,10,6]

In [399]:
header_numeric[columns_index_order]

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [400]:
header_numeric = header_numeric[columns_index_order]; 

In [401]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [402]:
arr_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [403]:
arr_numeric = arr_numeric[:,columns_index_order]

### Pré-Processamento da Variável int_rate

In [404]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [405]:
arr_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [406]:
# Vamos apenas dividir por 100
arr_numeric[:,5] = arr_numeric[:,5] / 100

In [407]:
arr_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

## Checkpoint com Variáveis Numéricas Limpas e Pré-Processadas

**Checkpoint 3**

In [ ]:
checkpoint_numeric = checkpoint("dados/Checkpoint-Numeric", header_numeric, arr_numeric)

In [ ]:
checkpoint_numeric['header'], checkpoint_numeric['data']

## Construindo o Dataset Final

In [ ]:
checkpoint_strings['data'].shape

In [ ]:
checkpoint_numeric['data'].shape

In [ ]:
# Concatena os arrays
df_final = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

In [ ]:
df_final

In [ ]:
# Verifica se tem valor ausente
np.isnan(df_final).sum()

In [ ]:
# Concatena os arrays de nomes de colunas
header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))

In [ ]:
# Ordenando o dataset
df_final = df_final[np.argsort(df_final[:,0])]

In [ ]:
df_final

In [ ]:
# Conferindo a ordenação da coluna 0
np.argsort(df_final[:,0])

## Gravando o Dataset Final Limpo e Pré-Processado

In [ ]:
# Concatena o array de nomes de colunas com o array de dados
df_final = np.vstack((header_full, df_final))

In [ ]:
# Salva em disco
np.savetxt("dados/dataset_limpo_preprocessado.csv", 
           df_final, 
           fmt = '%s',
           delimiter = ',')